apiVersion: v1
name: aws-cloud-controller-manager-app
description: A Helm chart to run AWS Cloud Controller Manager.
version: 2.0.0
appVersion: 1.33.2
home: https://github.com/giantswarm/aws-cloud-controller-manager-app
icon: https://s.giantswarm.io/app-icons/aws/2/dark.svg
annotations:
  application.giantswarm.io/team: phoenix
  ui.giantswarm.io/logo: https://s.giantswarm.io/app-icons/aws/2/dark.svg
restrictions:
  clusterSingleton: true
  fixedNamespace: kube-system
  gpuInstances: false
  compatibleProviders: [aws]
